name: Build & Release

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
      - "v*.*.*"
jobs:
  build:
    name: Build and Release
    # runs-on: windows-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Display dotnet version
        run: dotnet --version
      - name: Publish
        run: dotnet publish --configuration Release
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/Release/netcoreapp3.1/win-x64/publish/TwitchTeamLiveStats.exe
            bin/Release/netcoreapp3.1/win-x64/publish/appsettings.json
          generate_release_notes: true